# Generated by Django 3.2.6 on 2021-08-03 16:16

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0003_auto_20210803_0409'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModifierGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item')),
            ],
        ),
        migrations.CreateModel(
            name='Modifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, validators=[django.core.validators.MinValueValidator(limit_value=0.0, message='Cannot have a negative Price')])),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modifiers.modifiergroup')),
            ],
        ),
    ]
