# Generated by Django 3.2.6 on 2021-08-03 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20210803_0409'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LineItem',
        ),
    ]
